baseURL = "/"
languageCode = "en-us"
title = "CCAWMU"
relativeURLs = true
canonifyURLs = false
enableRobotsTXT = true
ignoreErrors = ["error-disable-taxonomy"]

[markup.goldmark.renderer]
unsafe = true

[params]
	description = "WMU's Resident Hackerspace Since 1976."
	underConstruction = false
